---
# tasks file for add_ec2_to_elb

- name: add ec2 to elastic load balancer
  ec2_elb:
    region: "{{ aws_region }}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    instance_id: "{{ item['tagged_instances'][0]['id'] }}"
    ec2_elbs: 
      - "{{ aws_elb_name }}"
    state: present
    wait: no
  with_items: "{{ hostvars['localhost']['ec2']['results'] }}"



